const JOB_STATES = {
    DISCOVERED: "DISCOVERED",
    RESEARCHING: "RESEARCHING",
    RESEARCH_READY: "RESEARCH_READY",
    SCRIPTING: "SCRIPTING",
    PRODUCTION: "PRODUCTION",
    FINAL_QA: "FINAL_QA",
    WAITING_APPROVAL: "WAITING_APPROVAL",
    APPROVED: "APPROVED",
    SCHEDULED: "SCHEDULED",
    PUBLISHED: "PUBLISHED",
    ANALYZING: "ANALYZING",
    LEARNED: "LEARNED",
    FAILED: "FAILED",
    CANCELLED: "CANCELLED",
};

module.exports = JOB_STATES;